#FROM bitnami/postgresql:latest
#FROM bitnami/postgresql:17.2.0

FROM postgis/postgis


# Adds extenstions:
# postgis_topology
# postgis_tiger_geocoder


# Enable the extension:
# CREATE EXTENSION postgis;




